theme: jekyll-theme-cayman
title: Spanish for Beginners
description: A fun introduction to the Spanish world
github:
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: page6.html
